version: "3.9"

services:
  server:
    build: ./server
    container_name: ignis_server
    ports:
      - "3001:3001"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/converted:/app/converted
      - ./server/output_metadata:/app/output_metadata
      - ./server/config:/app/config
    environment:
      - NODE_ENV=production
      - UPLOADS_DIR=/app/uploads
      - CONVERTED_DIR=/app/converted
      - OUTPUT_METADATA_DIR=/app/output_metadata

  client:
    build: ./client
    container_name: ignis_client
    ports:
      - "3000:80"
